export default [
      {
        id:1,
        tag:'aa',
        name:'折扣商品',
        icon:'',
        dishs:[
          {
            id:1,
            price:89,
            name:'石锅鱼',
            pic:'dish-9.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'石锅牛蛙',
            pic:'dish-10.jpg',
            count:0
          }
        ]
      },
      {
        id:2,
        tag:'bb',
        name:'凉菜',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'白切羊肉',
            pic:'dish-5.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'酸醉蟹钳',
            pic:'dish-6.jpg',
            count:0
          }
        ]
      },
      {
        id:3,
        tag:'cc',
        name:'蒸菜',
        icon:'',
        dishs:[
          {
            id:1,
            price:26,
            name:'武昌鱼',
            pic:'dish-3.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'清蒸草鱼',
            pic:'dish-4.jpg',
            count:0
          }
        ]
      },
      {
        id:4,
        tag:'dd',
        name:'汤羹',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'什锦鲜菇汤',
            pic:'dish-7.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'番茄蛋汤',
            pic:'dish-8.jpg',
            count:0
          }
        ]
      },
      {
        id:5,
        tag:'ee',
        name:'米饭',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            pic:'dish-2.jpg',
            count:0
          }
        ]
      },
      {
        id:6,
        tag:'ff',
        name:'套餐',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            pic:'dish-2.jpg',
            count:0
          }
        ]
      }
    ]